#!/usr/bin/env bash
# Homebrew mirror profiles + persistence.
#
# Authoritative help pages (refresh URLs via scripts/update-mirrors.sh):
#   tuna:  https://mirrors.tuna.tsinghua.edu.cn/help/homebrew/
#   ustc:  https://mirrors.ustc.edu.cn/help/brew.git.html
#   bfsu:  https://mirrors.bfsu.edu.cn/help/homebrew/
#   ali:   https://developer.aliyun.com/mirror/homebrew
#   official: unset custom remotes (Homebrew defaults)

[[ -n "${_SHELL_INIT_MIRRORS_LOADED:-}" ]] && return 0
_SHELL_INIT_MIRRORS_LOADED=1

# shellcheck source=common.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common.sh"

SHELL_INIT_CONFIG_DIR="${SHELL_INIT_CONFIG_DIR:-$HOME/.config/shell-init}"
SHELL_INIT_MIRROR_FILE="${SHELL_INIT_MIRROR_FILE:-$SHELL_INIT_CONFIG_DIR/mirror}"
SHELL_INIT_MIRROR_ENV="${SHELL_INIT_MIRROR_ENV:-$SHELL_INIT_CONFIG_DIR/brew-mirror.env}"

normalize_mirror_id() {
  local id="${1:-}"
  id="$(printf '%s' "$id" | tr '[:upper:]' '[:lower:]')"
  case "$id" in
    tuna|tsinghua|thu) echo "tuna" ;;
    ustc|zhongke) echo "ustc" ;;
    ali|alibaba|aliyun) echo "ali" ;;
    bfsu|beiwai) echo "bfsu" ;;
    official|none|off|default|"") echo "official" ;;
    *)
      log_err "未知镜像: $1（支持: tuna|ustc|ali|bfsu|official）"
      return 1
      ;;
  esac
}

list_mirrors() {
  cat <<'EOF'
ID        说明
--------  ------------------------------------------
tuna      清华 Tuna（默认，国内常用）
ustc      中科大 USTC
ali       阿里云
bfsu      北京外国语大学 BFSU
official  官方源（不设置镜像环境变量）
EOF
}

# Sets HOMEBREW_* for the current process. Does not persist.
apply_mirror_env() {
  local id
  id="$(normalize_mirror_id "${1:-$BREW_MIRROR}")" || return 1
  BREW_MIRROR="$id"
  export BREW_MIRROR

  # Clear previous custom remotes first
  unset HOMEBREW_API_DOMAIN HOMEBREW_BOTTLE_DOMAIN \
    HOMEBREW_BREW_GIT_REMOTE HOMEBREW_CORE_GIT_REMOTE 2>/dev/null || true

  case "$id" in
    tuna)
      export HOMEBREW_INSTALL_FROM_API=1
      export HOMEBREW_API_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/api"
      export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"
      export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git"
      export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git"
      ;;
    ustc)
      export HOMEBREW_INSTALL_FROM_API=1
      export HOMEBREW_API_DOMAIN="https://mirrors.ustc.edu.cn/homebrew-bottles/api"
      export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.ustc.edu.cn/homebrew-bottles"
      export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.ustc.edu.cn/brew.git"
      export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.ustc.edu.cn/homebrew-core.git"
      ;;
    ali)
      export HOMEBREW_INSTALL_FROM_API=1
      export HOMEBREW_API_DOMAIN="https://mirrors.aliyun.com/homebrew-bottles/api"
      export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.aliyun.com/homebrew-bottles"
      export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.aliyun.com/homebrew/brew.git"
      export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.aliyun.com/homebrew/homebrew-core.git"
      ;;
    bfsu)
      export HOMEBREW_INSTALL_FROM_API=1
      export HOMEBREW_API_DOMAIN="https://mirrors.bfsu.edu.cn/homebrew-bottles/api"
      export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.bfsu.edu.cn/homebrew-bottles"
      export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.bfsu.edu.cn/git/homebrew/brew.git"
      export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.bfsu.edu.cn/git/homebrew/homebrew-core.git"
      ;;
    official)
      # Intentionally no custom domains; keep INSTALL_FROM_API if already set by brew
      export HOMEBREW_INSTALL_FROM_API=1
      ;;
  esac
}

# Write ~/.config/shell-init/{mirror,brew-mirror.env} for zsh / later runs
persist_mirror_choice() {
  local id env_body
  id="$(normalize_mirror_id "${1:-$BREW_MIRROR}")" || return 1

  if [[ "${DRY_RUN:-0}" == "1" ]]; then
    log_dry "持久化镜像选择 → $SHELL_INIT_MIRROR_FILE ($id)"
    return 0
  fi

  assert_under_home "$SHELL_INIT_CONFIG_DIR" || return 1
  mkdir -p "$SHELL_INIT_CONFIG_DIR"
  printf '%s\n' "$id" >"$SHELL_INIT_MIRROR_FILE"

  {
    echo "# Generated by shell-init — Homebrew mirror: $id"
    echo "# Sources: see shell-init/scripts/update-mirrors.sh"
    echo "export HOMEBREW_INSTALL_FROM_API=1"
    case "$id" in
      tuna)
        echo 'export HOMEBREW_API_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/api"'
        echo 'export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"'
        echo 'export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git"'
        echo 'export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git"'
        ;;
      ustc)
        echo 'export HOMEBREW_API_DOMAIN="https://mirrors.ustc.edu.cn/homebrew-bottles/api"'
        echo 'export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.ustc.edu.cn/homebrew-bottles"'
        echo 'export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.ustc.edu.cn/brew.git"'
        echo 'export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.ustc.edu.cn/homebrew-core.git"'
        ;;
      ali)
        echo 'export HOMEBREW_API_DOMAIN="https://mirrors.aliyun.com/homebrew-bottles/api"'
        echo 'export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.aliyun.com/homebrew-bottles"'
        echo 'export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.aliyun.com/homebrew/brew.git"'
        echo 'export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.aliyun.com/homebrew/homebrew-core.git"'
        ;;
      bfsu)
        echo 'export HOMEBREW_API_DOMAIN="https://mirrors.bfsu.edu.cn/homebrew-bottles/api"'
        echo 'export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.bfsu.edu.cn/homebrew-bottles"'
        echo 'export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.bfsu.edu.cn/git/homebrew/brew.git"'
        echo 'export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.bfsu.edu.cn/git/homebrew/homebrew-core.git"'
        ;;
      official)
        echo "# official: no custom HOMEBREW_* domain remotes"
        ;;
    esac
  } >"$SHELL_INIT_MIRROR_ENV"

  log_ok "已持久化 Homebrew 镜像: $id → $SHELL_INIT_MIRROR_ENV"
}

load_persisted_mirror() {
  if [[ -f "$SHELL_INIT_MIRROR_FILE" ]]; then
    local id
    id="$(tr -d '[:space:]' <"$SHELL_INIT_MIRROR_FILE")"
    if [[ -n "$id" ]]; then
      BREW_MIRROR="$id"
      export BREW_MIRROR
    fi
  fi
}
